apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl

spec:

  replicas: 1
  selectors:
    matchlabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          images: auth/service

--------------

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
    protocol: tcp
    port: 5000
    targetPort: 5000